name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & Push Frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nursery-management-frontend:latest

    - name: Build & Push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend/nursery
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nursery-management-backend:latest

    - name: Deploy to Cloud VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        script: |
          cd ~/Deploy-React-spring-mySQL
          docker-compose down || true
          docker-compose up -d 
